#! /bin/bash

VERSION="1.0.0"
DATE="29/07/2022"

echo "eolicas-newave-deck"
echo "Gerência de Metodologias e Modelos Energéticos - PEM / ONS"
echo "Versão ${VERSION} - ${DATE}"

USERINSTALLDIR=/usr/lib
INSTALLDIR=${USERINSTALLDIR}/eolicas-newave/deck

# Checks if application is installed
if [ ! -d $INSTALLDIR ]; then
    echo "Aplicação não encontrada..."
    exit 1
fi

RUN=$INSTALLDIR/main.py

echo "Ativando o ambiente virtual"
source $INSTALLDIR/venv/bin/activate

echo "Executando"
echo "------------------"

echo python3 $RUN $*
python3 $RUN $*

echo "------------------"
echo "Desativando o ambiente virtual"
deactivate
